package com.compilerexplorer.common;

public enum Tabs {
    PROJECT_INFO,
    PREPROCESSOR_VERSION_STDOUT,
    PREPROCESSOR_VERSION_STDERR,
    PREPROCESSOR_VERSION_OUTPUT,
    PREPROCESSOR_STDOUT,
    PREPROCESSOR_STDERR,
    PREPROCESSOR_OUTPUT,
    SOURCE_INFO,
    EXPLORER_SITE_INFO,
    EXPLORER_SITE_RAW_OUTPUT,
    EXPLORER_RAW_INPUT,
    EXPLORER_RAW_OUTPUT,
    EXPLORER_STDOUT,
    EXPLORER_STDERR,
    EXPLORER_OUTPUT,
    EXPLORER_EXEC_RESULT,
    EXPLORER_OUTPUT_DEVICE_1,
    EXPLORER_OUTPUT_DEVICE_2,
    EXPLORER_OUTPUT_DEVICE_3,
    EXPLORER_OUTPUT_DEVICE_4,
    EXPLORER_OUTPUT_DEVICE_5,
    EVERYTHING
}
